[project]
name = "pdm-bump"
version = "0.4.4"
readme = "README.md"
description = "A plugin for PDM providing the ability to modify the version according to PEP440"
authors = [
    {name = "Carsten Igel", email = "cig@bite-that-bit.de"},
]
dependencies = [
    "pdm~=1.8",
    "pep440-version-utils~=0.3",
]
requires-python = ">=3.8"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/carstencodes/pdm-bump"

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]

[project.entry-points.pdm]
pdm-bump = "pdm_bump:main"
