[project]
name = "pdm-bump"
version = "0.4.10"
readme = "README.md"
description = "A plugin for PDM providing the ability to modify the version according to PEP440"
authors = [
    {name = "Carsten Igel", email = "cig@bite-that-bit.de"},
]
dependencies = [
    "pdm>=2.00",
    "pep440-version-utils~=0.3",
    "annotated-types>=0.2.0",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/carstencodes/pdm-bump"

[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.1.2",
    "tox>=3.25.1",
    "tox-pdm>=0.6.0",
    "pytest-cov>=3.0.0",
]
codestyle = [
    "flake8>=3.9.2",
    "flake518>=1.2.3",
    "mypy>=0.971",
    "black>=22.6.0",
    "pylint>=2.14.5",
    "pycodestyle>=2.7.0",
]

[tool.pytest.ini_options]
testpaths = [ "tests" ]
junit_suite_name = "pdm-bump"
pythonpath = [ "src" ]
minversion = "7.0.0"

[tool.tox]
legacy_tox_ini = """
[tox]
minversion = 3.25.0
requires = tox-pdm
skip_missing_interpreters = false
env_list = py{39, 310}
isolated_build = true

[testenv]
setenv = 
    PDM_IGNORE_SAVED_PYTHON="1"
deps = pdm
commands =
    pdm install --dev
    pytest tests
"""

[project.entry-points.pdm]
pdm-bump = "pdm_bump:main"
