name: PullRequest validation

on:
  pull_request:
    branches:
      - main
      - staging
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Set PDM version
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'pdm'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: ${{ env.pdm_version }}
          prerelease: true
          enable-pep582: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install production dependencies
        run: pdm install --prod
      - name: Build wheel
        run: pdm build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Set PDM version
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'pdm'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: ${{ env.pdm_version }}
          prerelease: true
          enable-pep582: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: pdm install --dev
      - name: Run unit tests
        run: pdm run pytest

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Set PDM version
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'pdm'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: ${{ env.pdm_version }}
          prerelease: true
          enable-pep582: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: pdm install --dev
      - name: Run linters
        run: pdm check-style

  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: Set PDM version
        uses: deep-mm/set-variables@v1.0
        with:
          variableFileName: 'pdm'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          version: ${{ env.pdm_version }}
          prerelease: true
          enable-pep582: true
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: pdm install --dev
      - name: Run linters
        run: pdm format
      - name: Check for changed files
        run: |
          no_changed_files=$(git status --porcelain | wc -l)
          if [ $no_changed_files -lt 0 ];
          then
            echo "There are changed files:" >&2
            git status --porcelain >&2
            exit 1
          fi
