name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch entire history
      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1
      - name: Generate changelog
        run: |
          git cliff --verbose --latest --strip all --output CHANGELOG.md
      - name: Export changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md
  deploy:
    name: Deploy wheel to pypi
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pdm
        pdm install -G:all
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pdm build
        twine upload dist/*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [ changelog, deploy ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog
          path: ${{ github.workspace }}/CHANGELOG.md
      - name: Create Release
        id: create_release
        run: |
          pre=
          case ${{ github.ref_name }} in
            v0*)
            *-dev*)
            *-pre*)
              pre=--prerelease;;
          esac

          gh release create ${{ github.ref_name }} -F "${{ github.workspace }}/CHANGELOG.md" $pre --title "Release ${{ github.ref_name }}" --repo ${{ github.repository }}
